apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      #- image: pawanitzone/hyt-http:28
      - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:6e325b86566fafd3c4683a05a219c30c421fbccbf8d87ab9d20d4ec1131c3451
        name: guestbook-ui
        ports:
        - containerPort: 80
